In [1]:
import pandas as pd
from tensorflow import keras
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn import metrics

In [2]:
#Importing the data set

df = pd.read_csv('Mobile_Dataset.csv')

In [3]:
#Display data columns

df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [4]:
#display the data table shape

df.shape

(2000, 21)

In [5]:
#display data type of each column

df.dtypes

battery_power      int64
blue               int64
clock_speed      float64
dual_sim           int64
fc                 int64
four_g             int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
three_g            int64
touch_screen       int64
wifi               int64
price_range        int64
dtype: object

In [6]:
#Checking for null values in each data entry

df.isnull()

battery_power   blue  clock_speed  dual_sim     fc  four_g  int_memory  \
0             False  False        False     False  False   False       False   
1             False  False        False     False  False   False       False   
2             False  False        False     False  False   False       False   
3             False  False        False     False  False   False       False   
4             False  False        False     False  False   False       False   
...             ...    ...          ...       ...    ...     ...         ...   
1995          False  False        False     False  False   False       False   
1996          False  False        False     False  False   False       False   
1997          False  False        False     False  False   False       False   
1998          False  False        False     False  False   False       False   
1999          False  False        False     False  False   False       False   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width    ram   sc_h  \
0     False      False    False  ...      False     False  False  False   
1     False      False    False  ...      False     False  False  False   
2     False      False    False  ...      False     False  False  False   
3     False      False    False  ...      False     False  False  False   
4     False      False    False  ...      False     False  False  False   
...     ...        ...      ...  ...        ...       ...    ...    ...   
1995  False      False    False  ...      False     False  False  False   
1996  False      False    False  ...      False     False  False  False   
1997  False      False    False  ...      False     False  False  False   
1998  False      False    False  ...      False     False  False  False   
1999  False      False    False  ...      False     False  False  False   

       sc_w  talk_time  three_g  touch_screen   wifi  price_range  
0     False      False    False         False  False        False  
1     False      False    False         False  False        False  
2     False      False    False         False  False        False  
3     False      False    False         False  False        False  
4     False      False    False         False  False        False  
...     ...        ...      ...           ...    ...          ...  
1995  False      False    False         False  False        False  
1996  False      False    False         False  False        False  
1997  False      False    False         False  False        False  
1998  False      False    False         False  False        False  
1999  False      False    False         False  False        False  

[2000 rows x 21 columns]

In [7]:
#Obtaining the total number of cells with null values in each column

df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [8]:
#Analyzing the dataset

analysis = df.describe()
print(analysis)

       battery_power       blue  clock_speed     dual_sim           fc  \
count    2000.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     0.4950     1.522250     0.509500     4.309500   
std       439.418206     0.5001     0.816004     0.500035     4.341444   
min       501.000000     0.0000     0.500000     0.000000     0.000000   
25%       851.750000     0.0000     0.700000     0.000000     1.000000   
50%      1226.000000     0.0000     1.500000     1.000000     3.000000   
75%      1615.250000     1.0000     2.200000     1.000000     7.000000   
max      1998.000000     1.0000     3.000000     1.000000    19.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  ...  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  ...   
mean      0.521500    32.046500     0.501750   140.249000     4.520500  ...   
std       0.499662    18.145715     0.288416    35.399655     2.287837  ...   
min       0.00000

In [9]:
#Converting data entries into values

dataset = df.values
print(dataset)

[[8.420e+02 0.000e+00 2.200e+00 ... 0.000e+00 1.000e+00 1.000e+00]
 [1.021e+03 1.000e+00 5.000e-01 ... 1.000e+00 0.000e+00 2.000e+00]
 [5.630e+02 1.000e+00 5.000e-01 ... 1.000e+00 0.000e+00 2.000e+00]
 ...
 [1.911e+03 0.000e+00 9.000e-01 ... 1.000e+00 0.000e+00 3.000e+00]
 [1.512e+03 0.000e+00 9.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 [5.100e+02 1.000e+00 2.000e+00 ... 1.000e+00 1.000e+00 3.000e+00]]


In [10]:
#Imputation of missing values
#The missing values(Null values and nonnumeric values) are replaced with the mean value of the specific column 

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(dataset)
print(dataset)

[[8.420e+02 0.000e+00 2.200e+00 ... 0.000e+00 1.000e+00 1.000e+00]
 [1.021e+03 1.000e+00 5.000e-01 ... 1.000e+00 0.000e+00 2.000e+00]
 [5.630e+02 1.000e+00 5.000e-01 ... 1.000e+00 0.000e+00 2.000e+00]
 ...
 [1.911e+03 0.000e+00 9.000e-01 ... 1.000e+00 0.000e+00 3.000e+00]
 [1.512e+03 0.000e+00 9.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 [5.100e+02 1.000e+00 2.000e+00 ... 1.000e+00 1.000e+00 3.000e+00]]


In [11]:
#Discrete optimization using casting inputs

dataset = dataset.astype('float32')
print(dataset)

[[8.420e+02 0.000e+00 2.200e+00 ... 0.000e+00 1.000e+00 1.000e+00]
 [1.021e+03 1.000e+00 5.000e-01 ... 1.000e+00 0.000e+00 2.000e+00]
 [5.630e+02 1.000e+00 5.000e-01 ... 1.000e+00 0.000e+00 2.000e+00]
 ...
 [1.911e+03 0.000e+00 9.000e-01 ... 1.000e+00 0.000e+00 3.000e+00]
 [1.512e+03 0.000e+00 9.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 [5.100e+02 1.000e+00 2.000e+00 ... 1.000e+00 1.000e+00 3.000e+00]]


In [12]:
#Defining input features (X) and predicting features (Y) 
x = dataset[:,0:20]
y = dataset[:,20]

In [13]:
#Normalization of x data using MinMax scaler function

min_max_scaler = preprocessing.MinMaxScaler()
x = min_max_scaler.fit_transform(x)
print(x)

[[0.22778893 0.         0.68000007 ... 0.         0.         1.        ]
 [0.3473614  1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.9418838  0.         0.15999998 ... 1.         1.         0.        ]
 [0.6753508  0.         0.15999998 ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]


In [14]:
#Splitting the data set into training data set and (testing and validation) data set. 80% as the training data set and 20% as the testing and validation data set. 

x_train, x_val_and_test, y_train, y_val_and_test = train_test_split(x, y, test_size=0.2)

print ("x_train shape = ", x_train.shape)
print ("x_validate and test shape = ", x_val_and_test.shape)

x_train shape =  (1600, 20)
x_validate and test shape =  (400, 20)


In [15]:
#Splitting the (testing and validation) dataset into testing and validation data. 50% as testing data and 50% as validation data. 

x_val, x_test, y_val, y_test = train_test_split(x_val_and_test, y_val_and_test , test_size=0.5)

print ("x_validate shape = ", x_val.shape)
print ("x_test shape = ", x_test.shape)

x_validate shape =  (200, 20)
x_test shape =  (200, 20)


In [16]:
#Defining the keras model
#Hidden Layer 01 : 512 neurons , RELU function
#Hidden Layer 02 : 512 neurons , RELU function
#Output Layer : 1 neuron , sigmoid function
#Input Shape : 20, since 20 input featuers are available

from keras.models import Sequential
from keras.layers import Dense

model = Sequential([
    Dense(256, activation='relu', input_shape=(20,)),
    Dense(256, activation='relu'),
    Dense(4, activation='softmax'),
])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 256)               5376      
                                                                 
 dense_1 (Dense)             (None, 256)               65792     
                                                                 
 dense_2 (Dense)             (None, 4)                 1028      
                                                                 
Total params: 72,196
Trainable params: 72,196
Non-trainable params: 0
_________________________________________________________________


In [17]:
#Compiling the model
from tensorflow.keras.optimizers import Adam

model.compile(optimizer='Adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [18]:
#Fitting the model 

BATCH_SIZE = 100
EPOCHES = 100
VERBOSE = 1
VALIDATION_SPLIT = 0.2 

model_history = model.fit(x_train,y_train, batch_size=BATCH_SIZE,epochs=EPOCHES, verbose=VERBOSE)


Epoch 1/100
16/16 [==============================] - 3s 10ms/step - loss: 1.3231 - accuracy: 0.3850
Epoch 2/100
16/16 [==============================] - 0s 6ms/step - loss: 1.1148 - accuracy: 0.6087
Epoch 3/100
16/16 [==============================] - 0s 8ms/step - loss: 0.8581 - accuracy: 0.7044
Epoch 4/100
16/16 [==============================] - 0s 9ms/step - loss: 0.6596 - accuracy: 0.7775
Epoch 5/100
16/16 [==============================] - 0s 8ms/step - loss: 0.5344 - accuracy: 0.8331
Epoch 6/100
16/16 [==============================] - 0s 22ms/step - loss: 0.4473 - accuracy: 0.8544
Epoch 7/100
16/16 [==============================] - 0s 23ms/step - loss: 0.3858 - accuracy: 0.8888
Epoch 8/100
16/16 [==============================] - 0s 5ms/step - loss: 0.3322 - accuracy: 0.9044
Epoch 9/100
16/16 [==============================] - 0s 5ms/step - loss: 0.2957 - accuracy: 0.9075
Epoch 10/100
16/16 [==============================] - 0s 6ms/step - loss: 0.2596 - accuracy: 0.9287
Epoch 

In [19]:
#Evaluate the model 
#Evaluating Method : Accuracy

model_accuracy = model.evaluate(x_test, y_test)[1]
print('Model accuracy:', model_accuracy)
#print("Accuracy on training set: {:.2%}".format(model.score(X_train, y_train)))
#print("Accuracy on test set: {:.2%}".format(model.score(X_test, y_test)))

7/7 [==============================] - 2s 31ms/step - loss: 0.2700 - accuracy: 0.8900
Model accuracy: 0.8899999856948853


In [20]:
#Evaluate the model 
#Evaluating Method : Precision, Recall and F-1 score

y_probs = model.predict(x_test)
y_pred  = np.argmax(y_probs, axis=-1)

print(metrics.classification_report(y_test, y_pred))

7/7 [==============================] - 1s 9ms/step
              precision    recall  f1-score   support

         0.0       0.92      0.96      0.94        49
         1.0       0.91      0.88      0.89        48
         2.0       0.83      0.87      0.85        52
         3.0       0.90      0.86      0.88        51

    accuracy                           0.89       200
   macro avg       0.89      0.89      0.89       200
weighted avg       0.89      0.89      0.89       200

